/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_FILES_H500_AVIONIC_PB_H_INCLUDED
#define PB_PROTO_FILES_H500_AVIONIC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _h500_avionics {
    int32_t latitude;
    int32_t longitude;
    int32_t sats;
    int32_t humidity;
    int32_t temperatureC_dht;
    int32_t acceleration_x;
    int32_t acceleration_y;
    int32_t acceleration_z;
    int32_t gyro_x;
    int32_t gyro_y;
    int32_t gyro_z;
    int32_t pressure;
    int32_t altGY;
    int32_t altMaxGY;
    int32_t temperatureC_GY;
    int32_t airspeed_ms;
    int32_t expected_latitude;
    int32_t expected_longitude;
} h500_avionics;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define h500_avionics_init_default               {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define h500_avionics_init_zero                  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define h500_avionics_latitude_tag               1
#define h500_avionics_longitude_tag              2
#define h500_avionics_sats_tag                   3
#define h500_avionics_humidity_tag               4
#define h500_avionics_temperatureC_dht_tag       5
#define h500_avionics_acceleration_x_tag         6
#define h500_avionics_acceleration_y_tag         7
#define h500_avionics_acceleration_z_tag         8
#define h500_avionics_gyro_x_tag                 9
#define h500_avionics_gyro_y_tag                 10
#define h500_avionics_gyro_z_tag                 11
#define h500_avionics_pressure_tag               12
#define h500_avionics_altGY_tag                  13
#define h500_avionics_altMaxGY_tag               14
#define h500_avionics_temperatureC_GY_tag        15
#define h500_avionics_airspeed_ms_tag            16
#define h500_avionics_expected_latitude_tag      17
#define h500_avionics_expected_longitude_tag     18

/* Struct field encoding specification for nanopb */
#define h500_avionics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   latitude,          1) \
X(a, STATIC,   SINGULAR, SINT32,   longitude,         2) \
X(a, STATIC,   SINGULAR, SINT32,   sats,              3) \
X(a, STATIC,   SINGULAR, SINT32,   humidity,          4) \
X(a, STATIC,   SINGULAR, SINT32,   temperatureC_dht,   5) \
X(a, STATIC,   SINGULAR, SINT32,   acceleration_x,    6) \
X(a, STATIC,   SINGULAR, SINT32,   acceleration_y,    7) \
X(a, STATIC,   SINGULAR, SINT32,   acceleration_z,    8) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_x,            9) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_y,           10) \
X(a, STATIC,   SINGULAR, SINT32,   gyro_z,           11) \
X(a, STATIC,   SINGULAR, SINT32,   pressure,         12) \
X(a, STATIC,   SINGULAR, SINT32,   altGY,            13) \
X(a, STATIC,   SINGULAR, SINT32,   altMaxGY,         14) \
X(a, STATIC,   SINGULAR, SINT32,   temperatureC_GY,  15) \
X(a, STATIC,   SINGULAR, SINT32,   airspeed_ms,      16) \
X(a, STATIC,   SINGULAR, SINT32,   expected_latitude,  17) \
X(a, STATIC,   SINGULAR, SINT32,   expected_longitude,  18)
#define h500_avionics_CALLBACK NULL
#define h500_avionics_DEFAULT NULL

extern const pb_msgdesc_t h500_avionics_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define h500_avionics_fields &h500_avionics_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_FILES_H500_AVIONIC_PB_H_MAX_SIZE   h500_avionics_size
#define h500_avionics_size                       111

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
